#!/usr/bin/python
# -*- coding: utf-8 -*-
# installation of psycopg2 http://initd.org/psycopg/docs/install.html

import psycopg2

connection = None

try:
    # Provide the connection properties to database. 
    # These are same as used in any database connection client.
    connection = psycopg2.connect(host='localhost', port = '5432', database='springHibernateWebApp', user='postgres',  password='postgres') 
    
    #Execute the statement on database
    cursor = connection.cursor()
    cursor.execute("select email,first_name, last_name, role, status from users ")          
    
    #Fetch and iterate over the result.
    rows = cursor.fetchall()
    for row in rows:
        email = row[0];
        firstName = row[1];
        lastName = row[2];
        role = row[3];
        status = row[4];
        
        print 'User details ' + 'email: ' + email
        
#catch if  exception happens
except psycopg2.DatabaseError, exception:
    print 'Exception  %s' % exception    
    sys.exit(1)
    
#Abnormal or normal, release the connection
finally:    
    if connection:
        connection.close()